### ISSUE TITLE
Cause tracker bug in DropItemEvent.Pre

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/Sponge#1280]
Steps to reproduce:
1.) Listen for `DropItemEvent.Pre`
2.) Call `event.getDroppedItems().clear()` in listener
3.) Spawn mob using /summon and kill it by hand
4.) The following happens: https://pastebin.com/6RFGQ2FU

Also I should note that I tried adding to `event.getDroppedItems()`, but that has no effect.

Tested on _SpongeVanilla 1.11.2-6.0.0-BETA-239_.

**Comment by gabizou** [comment]
I can fix this, however, please copy the *correct* log, since this one has artificial new lines added in several places, making it difficult to read.

**Comment by TheRaspPie** [comment]
I'm sorry, I copied the log from the windows console.. bad idea.
Here's the log from latest.log: https://pastebin.com/9XuZwrn8

**Comment by TheRaspPie** [comment]
Any updates on this? I don't want to be rude, but an essential plugin feature depends on this issue being resolved :)

**Comment by TheRaspPie** [comment]
There is another bug:
When cancelling DropItemEvent.Dispense the item drops anyway.
And when cancelling DropItemEvent (top-level):
 - The item isn't dropped if I drop it with Q
 - The item is dropped if I drop it through the inventory

EDIT (21 August):
When trying to drop the item by closing the inventory with the item as cursor, the DropItemEvent.Custom got fired instead of DropItemEvent.Dispense.
But if I cancel that event, the item just doesn't drop and disappears from the inventory.

To re-add the item to the inventory after closing it, I added this into MixinContainer.java as a workaround:

```java
    /**
     * @author TheRaspPie
     * @reason If dropped item is null (nothing gets dropped), re-add the item stack.
     */
    @Overwrite
    public void onContainerClosed(EntityPlayer playerIn)
    {
        InventoryPlayer inventoryplayer = playerIn.inventory;

        if (!inventoryplayer.getItemStack().isEmpty())
        {
            ItemStack stack = inventoryplayer.getItemStack();
            Object res = playerIn.dropItem(stack, false);
            inventoryplayer.setItemStack(ItemStack.EMPTY);
            if (res == null)
                inventoryplayer.addItemStackToInventory(stack);
        }
    }
```

**Comment by ImMorpheus** [comment]
This is still happening in 1.12 (bleeding branch)

The first bug:
The problem is with DropItemEvent.Pre only when it doesn't involve a player, rather that the whole event. As a proof try use /kill. There would be no stacktrace, but why ? When a player drops something, https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L981 is called, but there is a check to handle an empty list https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L1008. Now, spot the difference with https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L932. 
Fixed by changing that line to: `item = event.isCancelled() || dropEvent.getDroppedItems().isEmpty() ? null : ItemStackUtil.fromSnapshotToNative(dropEvent.getDroppedItems().get(0));`

EDIT:
The second bug (expanding some tests):
When cancelling DropItemEvent.Dispense:

- The item isn't dropped if I drop it with Q (without opening my inventory)
- The item isn't dropped if I drop it through the inventory (throwing it outside the inventory by hand)
- The item disappears if I open my inventory and press Q while hovering on the item
- The item is dropped if I open my inventory, take the item with the cursor and close the inventory. (That's because DropItemEvent.Custom is fired)

When cancelling DropItemEvent.Custom:
- The item disappears if I open my inventory, take the item with the cursor and close the inventory. 

When cancelling DropItemEvent:
- The only difference is that the item disappears if I drop it through the inventory (throwing it outside the inventory by hand)

**Comment by Faithcaio** [comment]
Should work now.

Except the item on your cursor when closing the inventory.

**Comment by ImMorpheus** [comment]
> Should work now.
> Except the item on your cursor when closing the inventory.

Can confirm. Everything is fixed aside that one.

**Comment by james58899** [comment]
any update?
cancel event still cause on cursor item disappear

**Comment by phit** [comment]
@ImMorpheus can you split this up into multiple issues for whatever is still an issue on latest? kinda hard to keep track whats still relevant here

**Comment by ImMorpheus** [comment]
Done. https://github.com/SpongePowered/SpongeCommon/issues/1879
