### ISSUE TITLE
Custom CommandElement throws wrong error

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/Sponge#1665]
I created my own `CommandElement`:

```java
package net.felixoi.felograms.command.element;

import net.felixoi.felograms.Felograms;
import net.felixoi.felograms.api.hologram.Hologram;
import net.felixoi.felograms.util.LocaleUtil;
import org.spongepowered.api.command.CommandSource;
import org.spongepowered.api.command.args.ArgumentParseException;
import org.spongepowered.api.command.args.CommandArgs;
import org.spongepowered.api.command.args.CommandContext;
import org.spongepowered.api.command.args.CommandElement;
import org.spongepowered.api.text.Text;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

public class HologramCommandElement extends CommandElement {

    public HologramCommandElement(Text key) {
        super(key);
    }

    @Override
    protected Object parseValue(CommandSource source, CommandArgs args) throws ArgumentParseException {
        String hologramID = args.next();

        Optional<Hologram> hologram = Felograms.getInstance().getHologramManager().getHologram(hologramID);
        if (hologram.isPresent()) {
            return hologram.get();
        } else {
            throw args.createError(Text.of("This hologram does not exists!"));
        }
    }

    @Override
    public List<String> complete(CommandSource src, CommandArgs args, CommandContext context) {
        List<String> choices = Felograms.getInstance().getHologramManager().getHolograms().stream().map(Hologram::getID).collect(Collectors.toList());

        final Optional<String> nextArg = args.nextIfPresent();
        if (nextArg.isPresent()) {
            choices = choices.stream().filter(hologramID -> hologramID.startsWith(nextArg.get())).collect(Collectors.toList());
        }

        return choices;
    }

}
```

It searches for holograms with the id and throws an error if it's not found. The error text is `This hologram does not exists!` but if I use this `CommandElement` with an unknown id the error message is `Too many arguments`:

![picture](https://i.gyazo.com/d17972c085dc5fecbff56a4d6cae4921.png)

**Comment by JBYoshi** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/37aebe9f78047a9a8600f5fdf3ff12ad36d4fe50.

**Comment by ryantheleach** [comment]
@JBYoshi Looking at the diff it isn't immediately obvious how this fixes the issue?

Can either you or @felixoi please confirm if this is actually fixed.

Also this may be related: https://github.com/SpongePowered/SpongeAPI/pull/1718

**Comment by dualspiral** [comment]
@felixoi This is a long standing issue - if you have child commands and a child argument fails to parse, it tries to fall back to the parent command. In this case, as you can see, it's fallen back to the parent command.

Are you using API 7? If so, in your parent `CommandSpec`, set `childArgumentParseExceptionFallback` to `false`.

**Comment by felixoi** [comment]
@JBYoshi Commit [37aebe9](https://github.com/SpongePowered/SpongeCommon/commit/37aebe9f78047a9a8600f5fdf3ff12ad36d4fe50) does not fix this issue!

@dualspiral Yes, I'm using API 7 and childArgumentParseExceptionFallback is already [set to false](https://github.com/felixoi/felograms/blob/master/src/main/java/net/felixoi/felograms/api/command/Command.java#L36).

**Comment by dualspiral** [comment]
Alright. I'll try to look at this tonight.

Could you possibly make a reduced test case for me? It'll make it easier for me to find the issue.

Thanks

**Comment by felixoi** [comment]
I build a test plugin for you: https://gist.github.com/felixoi/65ba84c2d85d4ed5c28330f3af15bdfa

The bug only appears with a custom `CommandElement` on child commands.

**Comment by dualspiral** [comment]
Thank you. I thought I'd tested this scenario, obviously I missed something somewhere. I'll get on to it tonight. :)

**Comment by dualspiral** [comment]
Solved it now. I'll push it - this is what the test plugin does now.

```
> commandelementtest
[12:34:29] [Server thread/INFO]: Command Executed
> commandlementtest test
[12:34:33] [Server thread/INFO]: Unknown command. Try /help for a list of commands
> commandelementtest test
[12:34:40] [Server thread/INFO]: Not enough arguments!
test
^
[12:34:40] [Server thread/INFO]: Usage: /commandelementtest test <test>
> commandelementtest test test
[12:34:47] [Server thread/INFO]: Command Child Executed
> commandelementtest test blah
[12:34:54] [Server thread/INFO]: Custom Command Element Exception
test blah
     ^
[12:34:54] [Server thread/INFO]: Usage: /commandelementtest test <test>
```
